-- Equipment & Input Sharing Feature for KrishiNayan
-- Community rental marketplace for farming equipment and input sharing
-- Run with `npx supabase db push` after linking the project

-- Equipment Listings Table
create table if not exists public.equipment_listings (
  id integer generated by default as identity primary key,
  owner_id integer not null references public.users(id) on delete cascade,
  
  -- Equipment Details
  equipment_type varchar not null,
  equipment_name varchar not null,
  brand varchar,
  model varchar,
  year_manufactured integer,
  condition varchar not null,
  
  -- Pricing
  rental_price_per_day double precision not null,
  rental_price_per_hour double precision,
  security_deposit double precision default 0,
  
  -- Location
  state varchar not null,
  district varchar not null,
  village varchar,
  latitude double precision not null,
  longitude double precision not null,
  location_description varchar,
  
  -- Availability
  is_available boolean default true,
  available_from date not null,
  available_until date,
  booked_dates jsonb,
  
  -- Media
  photos jsonb,
  primary_photo varchar,
  
  -- Description
  description text,
  specifications jsonb,
  usage_instructions text,
  safety_notes text,
  
  -- Status
  status varchar default 'active',
  verification_status varchar default 'pending',
  listing_quality_score double precision default 0,
  
  -- Metadata
  view_count integer default 0,
  inquiry_count integer default 0,
  rental_count integer default 0,
  
  created_at timestamp default now(),
  updated_at timestamp default now()
);

-- Equipment Rental Requests Table
create table if not exists public.equipment_rental_requests (
  id integer generated by default as identity primary key,
  listing_id integer not null references public.equipment_listings(id) on delete cascade,
  renter_id integer not null references public.users(id) on delete cascade,
  owner_id integer not null references public.users(id) on delete cascade,
  
  -- Rental Details
  requested_start_date date not null,
  requested_end_date date not null,
  requested_duration_hours integer,
  total_cost double precision not null,
  security_deposit_amount double precision,
  
  -- Status Workflow
  status varchar default 'pending',
  rejection_reason varchar,
  
  -- Communication
  message text,
  owner_response text,
  
  -- Pickup/Return
  pickup_location varchar,
  pickup_time varchar,
  return_condition varchar,
  return_notes text,
  
  -- Agreement
  agreed_terms boolean default false,
  agreement_signed_at timestamp,
  
  -- Completion
  actual_start_date date,
  actual_end_date date,
  actual_return_date date,
  
  created_at timestamp default now(),
  updated_at timestamp default now()
);

-- Equipment Reviews Table
create table if not exists public.equipment_reviews (
  id integer generated by default as identity primary key,
  rental_request_id integer not null references public.equipment_rental_requests(id) on delete cascade,
  listing_id integer not null references public.equipment_listings(id) on delete cascade,
  
  -- Reviewer info
  reviewer_id integer not null references public.users(id) on delete cascade,
  reviewee_id integer not null references public.users(id) on delete cascade,
  review_type varchar not null,
  
  -- Ratings
  overall_rating integer not null check (overall_rating >= 1 and overall_rating <= 5),
  equipment_condition_rating integer check (equipment_condition_rating >= 1 and equipment_condition_rating <= 5),
  communication_rating integer check (communication_rating >= 1 and communication_rating <= 5),
  punctuality_rating integer check (punctuality_rating >= 1 and punctuality_rating <= 5),
  value_rating integer check (value_rating >= 1 and value_rating <= 5),
  
  -- Review Content
  title varchar,
  comment text,
  
  -- Trust signals
  verified_rental boolean default true,
  helpful_count integer default 0,
  
  created_at timestamp default now(),
  updated_at timestamp default now()
);

-- Input Sharing Table (Phase 2)
create table if not exists public.input_sharing_listings (
  id integer generated by default as identity primary key,
  seller_id integer not null references public.users(id) on delete cascade,
  
  -- Input Details
  input_type varchar not null,
  input_name varchar not null,
  brand varchar,
  variety varchar,
  quantity double precision not null,
  unit varchar not null,
  
  -- Pricing
  price_per_unit double precision not null,
  negotiable boolean default false,
  minimum_quantity double precision,
  
  -- Quality
  quality_grade varchar,
  expiry_date date,
  batch_number varchar,
  certification_details varchar,
  
  -- Location
  state varchar not null,
  district varchar not null,
  village varchar,
  latitude double precision not null,
  longitude double precision not null,
  
  -- Availability
  is_available boolean default true,
  available_from date,
  
  -- Media
  photos jsonb,
  description text,
  
  -- Status
  status varchar default 'active',
  
  created_at timestamp default now(),
  updated_at timestamp default now()
);

-- Bulk Purchase Groups Table (Phase 2)
create table if not exists public.bulk_purchase_groups (
  id integer generated by default as identity primary key,
  organizer_id integer not null references public.users(id) on delete cascade,
  
  -- Group Details
  input_type varchar not null,
  input_name varchar not null,
  target_quantity double precision not null,
  current_quantity double precision default 0,
  unit varchar not null,
  
  -- Pricing
  target_price_per_unit double precision not null,
  estimated_savings_percentage double precision,
  
  -- Location
  state varchar not null,
  district varchar not null,
  meeting_point varchar,
  
  -- Timeline
  deadline date not null,
  pickup_date date,
  
  -- Status
  status varchar default 'open',
  
  -- Participants
  max_participants integer,
  current_participants integer default 0,
  
  created_at timestamp default now(),
  updated_at timestamp default now()
);

-- Bulk Purchase Participants Table (Phase 2)
create table if not exists public.bulk_purchase_participants (
  id integer generated by default as identity primary key,
  group_id integer not null references public.bulk_purchase_groups(id) on delete cascade,
  participant_id integer not null references public.users(id) on delete cascade,
  
  -- Commitment
  committed_quantity double precision not null,
  committed_amount double precision not null,
  
  -- Status
  status varchar default 'committed',
  
  -- Payment
  payment_status varchar default 'pending',
  payment_amount double precision,
  paid_at timestamp,
  
  created_at timestamp default now(),
  updated_at timestamp default now()
);

-- Equipment Categories Table
create table if not exists public.equipment_categories (
  id integer generated by default as identity primary key,
  name varchar not null unique,
  name_hi varchar,
  display_order integer default 0,
  icon varchar,
  is_active boolean default true,
  created_at timestamp default now()
);

-- User Equipment Trust Score Table
create table if not exists public.user_equipment_trust (
  id integer generated by default as identity primary key,
  user_id integer not null unique references public.users(id) on delete cascade,
  
  -- Trust Metrics
  overall_trust_score double precision default 50,
  as_owner_rating double precision,
  as_renter_rating double precision,
  
  -- Activity Metrics
  total_listings integer default 0,
  total_rentals_as_owner integer default 0,
  total_rentals_as_renter integer default 0,
  successful_completions integer default 0,
  cancellations integer default 0,
  disputes integer default 0,
  
  -- Verification
  identity_verified boolean default false,
  phone_verified boolean default false,
  equipment_verified_count integer default 0,
  
  -- Response Time
  average_response_time_hours double precision,
  
  updated_at timestamp default now()
);

-- Equipment Messages Table (for in-app chat)
create table if not exists public.equipment_messages (
  id integer generated by default as identity primary key,
  rental_request_id integer not null references public.equipment_rental_requests(id) on delete cascade,
  sender_id integer not null references public.users(id) on delete cascade,
  message text not null,
  message_type varchar default 'text', -- 'text', 'voice', 'system'
  voice_note_url varchar,
  is_read boolean default false,
  read_at timestamp,
  created_at timestamp default now()
);

-- Indexes for Equipment Search Performance
create index if not exists ix_equipment_listings_location on public.equipment_listings(state, district, status);
create index if not exists ix_equipment_listings_type_status on public.equipment_listings(equipment_type, status);
create index if not exists ix_equipment_listings_owner on public.equipment_listings(owner_id, status);
create index if not exists ix_equipment_listings_available_dates on public.equipment_listings(available_from, available_until, status);
create index if not exists ix_equipment_listings_coordinates on public.equipment_listings(latitude, longitude);
create index if not exists ix_equipment_listings_verification on public.equipment_listings(verification_status, status);

-- Rental Request Indexes
create index if not exists ix_equipment_rental_requests_listing on public.equipment_rental_requests(listing_id, status);
create index if not exists ix_equipment_rental_requests_renter on public.equipment_rental_requests(renter_id, status);
create index if not exists ix_equipment_rental_requests_owner on public.equipment_rental_requests(owner_id, status);
create index if not exists ix_equipment_rental_requests_dates on public.equipment_rental_requests(requested_start_date, requested_end_date);

-- Review Indexes
create index if not exists ix_equipment_reviews_listing on public.equipment_reviews(listing_id);
create index if not exists ix_equipment_reviews_reviewee on public.equipment_reviews(reviewee_id, review_type);
create index if not exists ix_equipment_reviews_rental on public.equipment_reviews(rental_request_id);

-- Input Sharing Indexes
create index if not exists ix_input_sharing_location on public.input_sharing_listings(state, district, status);
create index if not exists ix_input_sharing_type on public.input_sharing_listings(input_type, status);

-- Bulk Purchase Indexes
create index if not exists ix_bulk_purchase_groups_status on public.bulk_purchase_groups(status, deadline);
create index if not exists ix_bulk_purchase_participants_group on public.bulk_purchase_participants(group_id, status);

-- Trust Score Indexes
create index if not exists ix_user_equipment_trust_user on public.user_equipment_trust(user_id);
create index if not exists ix_user_equipment_trust_score on public.user_equipment_trust(overall_trust_score);

-- Message Indexes
create index if not exists ix_equipment_messages_request on public.equipment_messages(rental_request_id, created_at);
create index if not exists ix_equipment_messages_sender on public.equipment_messages(sender_id);

-- Row Level Security for Equipment Tables
alter table public.equipment_listings enable row level security;
alter table public.equipment_rental_requests enable row level security;
alter table public.equipment_reviews enable row level security;
alter table public.input_sharing_listings enable row level security;
alter table public.bulk_purchase_groups enable row level security;
alter table public.bulk_purchase_participants enable row level security;
alter table public.equipment_categories enable row level security;
alter table public.user_equipment_trust enable row level security;
alter table public.equipment_messages enable row level security;

-- Equipment Listings RLS Policies
create policy "owners can view own listings" on public.equipment_listings
  for select using (auth.uid()::integer = owner_id);

create policy "owners can insert own listings" on public.equipment_listings
  for insert with check (auth.uid()::integer = owner_id);

create policy "owners can update own listings" on public.equipment_listings
  for update using (auth.uid()::integer = owner_id);

create policy "owners can delete own listings" on public.equipment_listings
  for delete using (auth.uid()::integer = owner_id);

create policy "everyone can view active listings" on public.equipment_listings
  for select using (status = 'active' and is_available = true);

-- Rental Requests RLS Policies
create policy "users can view own requests" on public.equipment_rental_requests
  for select using (auth.uid()::integer = renter_id or auth.uid()::integer = owner_id);

create policy "renters can create requests" on public.equipment_rental_requests
  for insert with check (auth.uid()::integer = renter_id);

create policy "owners can update requests" on public.equipment_rental_requests
  for update using (auth.uid()::integer = owner_id);

create policy "renters can update own requests" on public.equipment_rental_requests
  for update using (auth.uid()::integer = renter_id);

-- Reviews RLS Policies
create policy "users can view all reviews" on public.equipment_reviews
  for select using (true);

create policy "verified renters can create reviews" on public.equipment_reviews
  for insert with check (
    auth.uid()::integer = reviewer_id and 
    verified_rental = true
  );

-- Input Sharing RLS Policies
create policy "sellers can view own listings" on public.input_sharing_listings
  for select using (auth.uid()::integer = seller_id);

create policy "sellers can insert own listings" on public.input_sharing_listings
  for insert with check (auth.uid()::integer = seller_id);

create policy "sellers can update own listings" on public.input_sharing_listings
  for update using (auth.uid()::integer = seller_id);

create policy "sellers can delete own listings" on public.input_sharing_listings
  for delete using (auth.uid()::integer = seller_id);

create policy "everyone can view active input listings" on public.input_sharing_listings
  for select using (status = 'active' and is_available = true);

-- Bulk Purchase RLS Policies
create policy "organizers can view own groups" on public.bulk_purchase_groups
  for select using (auth.uid()::integer = organizer_id);

create policy "organizers can create groups" on public.bulk_purchase_groups
  for insert with check (auth.uid()::integer = organizer_id);

create policy "organizers can update own groups" on public.bulk_purchase_groups
  for update using (auth.uid()::integer = organizer_id);

create policy "everyone can view open groups" on public.bulk_purchase_groups
  for select using (status = 'open');

-- Bulk Purchase Participants RLS Policies
create policy "participants can view own participations" on public.bulk_purchase_participants
  for select using (auth.uid()::integer = participant_id);

create policy "users can join groups" on public.bulk_purchase_participants
  for insert with check (auth.uid()::integer = participant_id);

create policy "participants can update own participations" on public.bulk_purchase_participants
  for update using (auth.uid()::integer = participant_id);

-- Equipment Categories RLS Policies
create policy "everyone can view categories" on public.equipment_categories
  for select using (is_active = true);

-- User Equipment Trust RLS Policies
create policy "users can view own trust" on public.user_equipment_trust
  for select using (auth.uid()::integer = user_id);

create policy "everyone can view trust scores" on public.user_equipment_trust
  for select using (true);

-- Messages RLS Policies
create policy "participants can view request messages" on public.equipment_messages
  for select using (
    auth.uid()::integer in (
      select renter_id from public.equipment_rental_requests where id = rental_request_id
      union
      select owner_id from public.equipment_rental_requests where id = rental_request_id
    )
  );

create policy "participants can send messages" on public.equipment_messages
  for insert with check (
    auth.uid()::integer = sender_id and
    auth.uid()::integer in (
      select renter_id from public.equipment_rental_requests where id = rental_request_id
      union
      select owner_id from public.equipment_rental_requests where id = rental_request_id
    )
  );

-- Insert default equipment categories
insert into public.equipment_categories (name, name_hi, icon, display_order) values
('tractor', 'ट्रैक्टर', '🚜', 1),
('harvester', 'हार्वेस्टर', '🌾', 2),
('sprayer', 'स्प्रेयर', '🧴', 3),
('sensor', 'सेंसर', '📡', 4),
('plow', 'हल', '🔨', 5),
('pump', 'पंप', '💧', 6),
('cultivator', 'कल्टीवेटर', '⚙️', 7),
('thresher', 'थ्रेशर', '🌾', 8)
on conflict (name) do nothing;

-- Create storage bucket for equipment photos
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'equipment-photos',
  'equipment-photos',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Create storage bucket for input photos
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'input-photos',
  'input-photos',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Create storage bucket for voice notes
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'voice-notes',
  'voice-notes',
  false,
  5242880,
  array['audio/mpeg', 'audio/wav', 'audio/ogg']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;