-- KrishiNayan production schema for Supabase PostgreSQL.
-- Run with `npx supabase db push` after linking the project, or paste into
-- Supabase SQL Editor for a one-time setup.

create table if not exists public.users (
  id integer generated by default as identity primary key,
  email varchar unique,
  phone varchar unique,
  password_hash varchar not null,
  role varchar default 'farmer',
  institutional_id varchar unique,
  organisation varchar,
  designation varchar,
  access_state varchar,
  access_district varchar,
  is_active boolean default true,
  full_name varchar not null,
  language varchar default 'en',
  state varchar,
  district varchar,
  village varchar,
  farm_size_acres double precision,
  crops varchar,
  irrigation_type varchar,
  farmer_category varchar,
  profile_completed boolean default false,
  identity_verification_status varchar default 'not_started',
  identity_verification_provider varchar,
  identity_verification_reference varchar,
  identity_verified_at timestamp,
  created_at timestamp default now(),
  updated_at timestamp default now()
);

create table if not exists public.farm_plots (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  name varchar not null,
  crop varchar not null,
  crop_label varchar not null,
  growth_stage varchar,
  sowing_date date,
  area_acres double precision,
  state varchar,
  district varchar,
  village varchar,
  latitude double precision,
  longitude double precision,
  created_at timestamp default now(),
  updated_at timestamp default now()
);

create table if not exists public.scan_records (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  crop varchar not null,
  crop_label varchar not null,
  field_label varchar not null,
  plot_id integer references public.farm_plots(id) on delete set null,
  disease varchar not null,
  confidence double precision not null,
  prediction_status varchar not null,
  severity varchar not null,
  health_score double precision not null,
  image_path varchar,
  state varchar,
  district varchar,
  latitude double precision,
  longitude double precision,
  treatment_cost_min double precision,
  treatment_cost_max double precision,
  created_at timestamp default now()
);

create table if not exists public.recovery_plans (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  plot_id integer references public.farm_plots(id) on delete set null,
  scan_record_id integer not null references public.scan_records(id) on delete cascade,
  crop varchar not null,
  crop_label varchar not null,
  disease varchar not null,
  status varchar default 'active',
  created_at timestamp default now()
);

create table if not exists public.recovery_tasks (
  id integer generated by default as identity primary key,
  plan_id integer not null references public.recovery_plans(id) on delete cascade,
  day integer not null,
  title varchar not null,
  description varchar not null,
  due_date date,
  best_time varchar,
  completed boolean default false,
  completed_at timestamp
);

create table if not exists public.officer_advisories (
  id integer generated by default as identity primary key,
  officer_user_id integer not null references public.users(id) on delete cascade,
  state varchar not null,
  district varchar,
  crop varchar,
  language varchar default 'en',
  title varchar not null,
  message text not null,
  created_at timestamp default now()
);

create table if not exists public.officer_registration_requests (
  id integer generated by default as identity primary key,
  full_name varchar not null,
  official_email varchar not null,
  institutional_id varchar not null,
  organisation varchar not null,
  designation varchar not null,
  state varchar not null,
  district varchar not null,
  status varchar not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists ix_users_email on public.users(email);
create index if not exists ix_users_phone on public.users(phone);
create index if not exists ix_users_role on public.users(role);
create index if not exists ix_users_institutional_id on public.users(institutional_id);
create index if not exists ix_farm_plots_user_id on public.farm_plots(user_id);
create index if not exists ix_farm_plots_crop on public.farm_plots(crop);
create index if not exists ix_farm_plots_location on public.farm_plots(state, district);
create index if not exists ix_scan_records_user_crop_field on public.scan_records(user_id, crop, field_label);
create index if not exists ix_scan_records_plot_id on public.scan_records(plot_id);
create index if not exists ix_scan_records_location_date on public.scan_records(state, district, created_at desc);
create index if not exists ix_scan_records_disease_date on public.scan_records(disease, created_at desc);
create index if not exists ix_recovery_plans_user_status on public.recovery_plans(user_id, status);
create index if not exists ix_recovery_tasks_plan_due on public.recovery_tasks(plan_id, due_date);
create index if not exists ix_officer_advisories_scope on public.officer_advisories(state, district, crop, created_at desc);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'crop-scans',
  'crop-scans',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/bmp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.users enable row level security;
alter table public.farm_plots enable row level security;
alter table public.scan_records enable row level security;
alter table public.recovery_plans enable row level security;
alter table public.recovery_tasks enable row level security;
alter table public.officer_advisories enable row level security;
alter table public.officer_registration_requests enable row level security;

-- The FastAPI backend should connect with the service role/database password,
-- which bypasses RLS. These deny-by-default policies protect the tables if a
-- browser Supabase client is introduced later before user-id claims are mapped.
drop policy if exists "deny direct users access" on public.users;
create policy "deny direct users access" on public.users for all using (false);

drop policy if exists "deny direct farm plots access" on public.farm_plots;
create policy "deny direct farm plots access" on public.farm_plots for all using (false);

drop policy if exists "deny direct scan records access" on public.scan_records;
create policy "deny direct scan records access" on public.scan_records for all using (false);

drop policy if exists "deny direct recovery plans access" on public.recovery_plans;
create policy "deny direct recovery plans access" on public.recovery_plans for all using (false);

drop policy if exists "deny direct recovery tasks access" on public.recovery_tasks;
create policy "deny direct recovery tasks access" on public.recovery_tasks for all using (false);

drop policy if exists "deny direct officer advisories access" on public.officer_advisories;
create policy "deny direct officer advisories access" on public.officer_advisories for all using (false);

drop policy if exists "deny direct officer registration requests access" on public.officer_registration_requests;
create policy "deny direct officer registration requests access" on public.officer_registration_requests for all using (false);
